### ISSUE TITLE
'BDCGAN' object has no attribute 'd_optim_semi_adam'

### ISSUE THREAD

**Issue by jlandesman** [andrewgordonwilson/bayesgan#3]
In attempting run the MNIST example (with the below, most basic command) I ran into the below error. 

```
Traceback (most recent call last):
  File "bayesgan/bayesian_gan_hmc.py", line 431, in <module>
    b_dcgan(dataset, args)
  File "bayesgan/bayesian_gan_hmc.py", line 158, in b_dcgan
    optimizer_dict = {"semi_d": dcgan.d_optim_semi_adam,
AttributeError: 'BDCGAN' object has no attribute 'd_optim_semi_adam'
```

My environment is compiled with the environment.yaml and my command to run the code is: 

bayesgan/bayesian_gan_hmc.py --data_path /home/jlandesman --dataset mnist --out_dir results/mnist --save_samples --n_save 100

The synth data appears to work well.

Any thoughts? 

Many thanks for your help and congratulations on the paper.

**Comment by cschuch** [comment]
@jlandesman 

The problem is that `d_optim_semi_adam` and `s_optim_adam` are only set on the BDCGAN if you're running everything for semi-supervised learning.

In order to get things working, in `bayesian_gan_hmc.py` on line 158 you can change

```
    optimizer_dict = {"semi_d": dcgan.d_optim_semi_adam,
                      "sup_d": dcgan.s_optim_adam,
                      "adv_d": dcgan.d_optim_adam,
                      "gen": dcgan.g_optims_adam}
```

to 
```
    if args.semi_supervised:
        optimizer_dict = {"semi_d": dcgan.d_optim_semi_adam,
                          "sup_d": dcgan.s_optim_adam,
                          "adv_d": dcgan.d_optim_adam,
                          "gen": dcgan.g_optims_adam}
    else:
        optimizer_dict = {"adv_d": dcgan.d_optim_adam,
                          "gen": dcgan.g_optims_adam}
```

I might put a PR up later, but thought I'd share here first. This seems to be working locally for me so far, but I haven't played around enough to know if this breaks anything elsewhere.

**Comment by ysaatchi** [comment]
Hey! Yes, this is a bug which I noticed also. It only happens in purely unsupervised learning, will fix and ping you.

**Comment by ysaatchi** [comment]
You're good to go :)
